# Generated by Django 5.0 on 2024-01-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('auto_feild', models.AutoField(primary_key=True, serialize=False)),
                ('big_integer_feild', models.BigIntegerField()),
                ('binary_feild', models.BinaryField()),
                ('boolean_feild', models.BooleanField()),
                ('char_feild', models.CharField(max_length=255)),
                ('email_feild', models.EmailField(max_length=254)),
                ('date_feild', models.DateField()),
                ('date_time_feild', models.DateTimeField()),
                ('decimal_feild', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_feild', models.DurationField()),
                ('file_field', models.FileField(upload_to='files/')),
                ('img', models.ImageField(unique='images/', upload_to='')),
                ('float_field', models.FloatField()),
                ('generic_ip_address_field', models.GenericIPAddressField()),
                ('integer_field', models.IntegerField()),
                ('json_field', models.JSONField()),
                ('slug_feild', models.SlugField()),
                ('small_integer_field', models.SmallIntegerField()),
                ('positive_small_integer_field', models.PositiveSmallIntegerField()),
                ('positive_big_integer_field', models.PositiveBigIntegerField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('time_field', models.TimeField()),
                ('url_field', models.URLField()),
                ('uuid_field', models.UUIDField()),
            ],
        ),
    ]
